apiVersion: v2
name: logging-lgf
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: fluent-bit
    version: "0.50.0"
    repository: "https://fluent.github.io/helm-charts"
    condition: fluent-bit.enabled

  - name: loki
    version: "6.35.1"
    repository: "https://grafana.github.io/helm-charts"
    condition: loki.enabled

  - name: grafana
    version: "9.3.1"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled