---
- name: Add the Bitnami Helm chart repository
  kubernetes.core.helm_repository:
    name: "bitnami"
    repo_url: "https://charts.bitnami.com/bitnami"

- name: Update Helm repository cache
  ansible.builtin.command:
    cmd: helm repo update

- name: Build Helm chart dependencies from local cache
  ansible.builtin.command:
    cmd: "helm dependency build {{ chart_path }}"

- name: "Deploy or upgrade the {{ chart_name }} Helm chart"
  kubernetes.core.helm:
    name: "{{ helm_release_name }}"
    chart_ref: "{{ chart_path }}"
    namespace: "{{ helm_namespace }}"
    create_namespace: yes
    values_files:
      - "{{ override_values_file_path }}"
    wait: yes
    timeout: 5m
    state: present
  tags:
    - helm-deploy