apiVersion: v1
kind: Service
metadata:
  name: audit-event-generator-service
  labels:
    app: audit-event-generator
spec:
  selector:
    app: audit-event-generator
  ports:
  - protocol: TCP
    port: 5000
    targetPort: http-app
    name: http-app
  - protocol: TCP
    port: 8000
    targetPort: http-metrics # For Prometheus scraping
    name: http-metrics
  type: ClusterIP # Only accessible from within the cluster