apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "audit-event-generator.fullname" . }}
  labels:
    {{- include "audit-event-generator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "audit-event-generator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }} 
      {{- end }}
      labels:
        {{- include "audit-event-generator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: default
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      {{- range .Values.waitFor }}
      {{ include "wait-for" (dict "Name" .name "Port" .port "Context" $) | nindent 6 }}
      {{- end }}

      containers:
      - name: generator-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          {{- $allEnv := list }}
          {{- range $key, $value := .Values.env }}
          {{- $allEnv = append $allEnv (dict "name" $key "value" (printf "%s" $value)) }}
          {{- end }}
          {{- $allEnv = append $allEnv (dict "name" "RABBITMQ_HOST" "value" (printf "%s-rabbitmq" .Release.Name)) }}
          {{- toYaml $allEnv | nindent 10 }}
        #   {{- range $key, $value := .Values.env }}
        # - name: {{ $key }}
        #   value: "{{ $value }}"
        #   {{- end }}
        ports:
        - containerPort: {{ .Values.service.appPort }}
          name: {{ .Values.service.appPortName }}
        - containerPort: {{ .Values.service.metricsPort }}
          name: {{ .Values.service.metricsPortName }}
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: "{{ .Values.livenessProbe.path }}"
            port: "{{ .Values.livenessProbe.port }}"
            scheme: HTTP
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: "{{ .Values.readinessProbe.port }}"
            scheme: HTTP
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}