# redis-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest # Using the latest Redis image. You can specify a version like redis:7-alpine for a smaller image.
        ports:
        - containerPort: 6379 # Default Redis port
        resources:
          limits:
            cpu: 100m
            memory: 128Mi # Adjust based on your cluster's capacity and expected Redis load
          requests:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        emptyDir: {} # Using emptyDir for simple, non-persistent storage. For production, consider persistent volumes.

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service # This is the DNS name your 'audit-log-analysis' app will use to connect
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379      # The port the service will listen on
      targetPort: 6379 # The port the Redis container is listening on
  type: ClusterIP # Default service type, makes it accessible within the cluster