---
- name: Ensure K3s node token is retrieved from master
  ansible.builtin.shell: cat /var/lib/rancher/k3s/server/node-token
  register: k3s_node_token_result
  delegate_to: "{{ groups['k3s_master'][0] }}"
  run_once: true
  become: true

- name: Set fact for K3s node token
  ansible.builtin.set_fact:
    k3s_node_token: "{{ k3s_node_token_result.stdout | trim }}"
  run_once: true

- name: Get K3s master IP address
  ansible.builtin.set_fact:
    k3s_master_ip: "{{ hostvars[groups['k3s_master'][0]]['ansible_host'] }}"
  run_once: true