---
- name: Deploy Kubernetes Services
  hosts: local
  gather_facts: no
  connection: local

  vars:
    helm_release_name: "{{ release_name_from_gha }}"
    helm_namespace: "{{ namespace_from_gha }}"
    chart_name: "{{ chart_name_from_gha }}"
    chart_path: "{{ playbook_dir }}/../../../k8s/charts/{{ chart_name_from_gha }}"
    values_file_path: "{{ chart_path }}/values.yaml"
    override_values_file_path: "{{ override_file_from_gha }}"

  roles:
    - deploy_k8s_services