name: "CD: Deploy to dev/staging/test"

on:
  workflow_dispatch:
    inputs:
      ref_name:
        description: 'The branch name that triggered the CI workflow.'
        required: true
        type: string
      github_sha:
        description: 'The commit SHA from the CI workflow.'
        required: true
        type: string
      docker_org:
        description: 'The Docker organization/user name.'
        required: true
        type: string
      docker_repo_prefix:
        description: 'The prefix for the Docker repository name.'
        required: true
        type: string
      changes:
        description: 'JSON object containing a map of service changes (src and k8s).'
        required: true
        type: string

jobs:
  prepare-helm-overrides:
    name: "Prepare Helm Overrides for ${{ inputs.ref_name }}"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Set override filename
        id: set_filename
        run: echo "OVERRIDE_FILENAME=deployment-overrides-${{ inputs.github_sha }}.yaml" >> $GITHUB_OUTPUT

      - name: Determine deployment namespace and base values file
        id: set_namespace_and_base_values
        run: |
          BRANCH_NAME="${{ inputs.ref_name }}"

          case "$BRANCH_NAME" in
            "feature/"*)
              TARGET_NAMESPACE="test"
              ;;
            "staging")
              TARGET_NAMESPACE="stg"
              ;;
            *)
              TARGET_NAMESPACE="$BRANCH_NAME"
              ;;
          esac

          DYNAMIC_VALUES_FILE="k8s/charts/values-${TARGET_NAMESPACE}.yaml"
          DEFAULT_VALUES_FILE="k8s/charts/values-test.yaml"

          if [ -f "$DYNAMIC_VALUES_FILE" ]; then
            BASE_VALUES_FILE_PATH="$DYNAMIC_VALUES_FILE"
            echo "Using dynamic base values file: $BASE_VALUES_FILE_PATH"
          else
            BASE_VALUES_FILE_PATH="$DEFAULT_VALUES_FILE"
            echo "Dynamic base values file ($DYNAMIC_VALUES_FILE) not found. Falling back to default: $BASE_VALUES_FILE_PATH"
          fi

          echo "Setting target namespace to: $TARGET_NAMESPACE"
          echo "namespace=$TARGET_NAMESPACE" >> $GITHUB_OUTPUT
          echo "base_values_file=$BASE_VALUES_FILE_PATH" >> $GITHUB_OUTPUT
          echo "$TARGET_NAMESPACE" > deployment_namespace_${{ inputs.github_sha }}.txt

      - name: Generate deployment override file
        id: generate_override
        env:
          BASE_VALUES_FILE: '${{ steps.set_namespace_and_base_values.outputs.base_values_file }}'
        run: python .github/scripts/generate_helm_override.py '${{ inputs.changes }}' '${{ inputs.github_sha }}' ${{ env.BASE_VALUES_FILE }} ${{ steps.set_filename.outputs.OVERRIDE_FILENAME }}

      - name: Store override file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-overrides-${{ inputs.github_sha }}
          path: ${{ steps.set_filename.outputs.OVERRIDE_FILENAME }}

      - name: Store namespace as artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-namespace-${{ inputs.github_sha }}
          path: deployment_namespace_${{ inputs.github_sha }}.txt

  deploy:
    name: "Deploy using Ansible"
    runs-on: [self-hosted, 'homelab-pi5']
    needs: prepare-helm-overrides

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.github_sha }}

      - name: Download deployment override file
        uses: actions/download-artifact@v4
        with:
          name: deployment-overrides-${{ inputs.github_sha }}
          path: /tmp

      - name: Download deployment namespace
        uses: actions/download-artifact@v4
        with:
          name: deployment-namespace-${{ inputs.github_sha }}
          path: /tmp

      - name: Read deployment namespace
        id: get_namespace
        run: |
          DEPLOYMENT_NAMESPACE=$(cat /tmp/deployment_namespace_${{ inputs.github_sha }}.txt)
          echo "Retrieved deployment namespace: $DEPLOYMENT_NAMESPACE"
          echo "namespace=$DEPLOYMENT_NAMESPACE" >> $GITHUB_OUTPUT

      - name: Setup Ansible environment and install dependencies
        working-directory: infra/ansible
        run: |
          # Install the Ansible Kubernetes collection from requirements.yml
          ansible-galaxy collection install -r requirements.yml
          
          # Install the necessary Python libraries for Ansible's Kubernetes modules
          pip3 install kubernetes pyyaml

      - name: Run Ansible Playbook for Deployment
        working-directory: infra/ansible
        run: |
          ansible-playbook playbooks/deploy_k8s_services.yml \
            --extra-vars "release_name_from_gha=${{ steps.get_namespace.outputs.namespace }}-afp" \
            --extra-vars "namespace_from_gha=${{ steps.get_namespace.outputs.namespace }}" \
            --extra-vars "chart_name_from_gha=auditflow-platform" \
            --extra-vars "override_file_from_gha=/tmp/deployment-overrides-${{ inputs.github_sha }}.yaml" \
            -vvv

  promote-images-after-deployment:
    name: "Promote Image Tags After Successful Deployment"
    runs-on: ubuntu-latest
    needs: deploy
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download deployment override file
        uses: actions/download-artifact@v4
        with:
          name: deployment-overrides-${{ inputs.github_sha }}
          path: /tmp

      - name: Download deployment namespace
        uses: actions/download-artifact@v4
        with:
          name: deployment-namespace-${{ inputs.github_sha }}
          path: /tmp

      - name: Read deployment namespace
        id: get_namespace
        run: |
          DEPLOYMENT_NAMESPACE=$(cat /tmp/deployment_namespace_${{ inputs.github_sha }}.txt)
          echo "Retrieved deployment namespace: $DEPLOYMENT_NAMESPACE"
          echo "namespace=$DEPLOYMENT_NAMESPACE" >> $GITHUB_OUTPUT # Output for use in subsequent steps

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run image promotion script
        env:
          OVERRIDE_FILE: /tmp/deployment-overrides-${{ inputs.github_sha }}.yaml
        run: |
          python3 .github/scripts/promote_images.py \
            --override-file ${{ env.OVERRIDE_FILE }} \
            --github-sha ${{ inputs.github_sha }} \
            --docker-org ${{ inputs.docker_org }} \
            --namespace ${{ steps.get_namespace.outputs.namespace }}