# audit_analysis_app/metrics.py

from prometheus_client import Counter, Gauge

# --- Prometheus Metrics Definitions ---
audit_analysis_processed_total = Counter('audit_analysis_processed_total', 'Total number of audit events processed.')
audit_analysis_alerts_total = Counter('audit_analysis_alerts_total', 'Total number of alerts generated by analysis.', ['alert_type', 'severity', 'user_id', 'server_hostname'])
rabbitmq_consumer_connection_status = Gauge('audit_analysis_rabbitmq_consumer_connection_status', 'Status of RabbitMQ consumer connection (1=connected, 0=disconnected).')
rabbitmq_messages_consumed_total = Counter('audit_analysis_rabbitmq_messages_consumed_total', 'Total number of messages consumed from RabbitMQ.')
redis_connection_status = Gauge('audit_analysis_redis_connection_status', 'Status of Redis connection (1=connected, 0=disconnected).')